# Generated by Django 5.0.1 on 2024-04-03 11:48

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0002_remove_expensesheet_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalReturnToCashier',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('employer_initiateur', models.CharField(max_length=255)),
                ('remaining_amount', models.FloatField()),
                ('description', models.TextField()),
                ('num_ref', models.CharField(db_index=True, max_length=255)),
                ('num_dossier', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(choices=[('VALIDATION CONFORMITE', 'VALIDATION_CONFORMITE'), ('REJET CONFORMITE', 'REJET_CONFORMITE'), ('VALIDATION BUDGETAIRE', 'VALIDATION_BUDGETAIRE'), ('REJET BUDGETAIRE', 'REJET_BUDGETAIRE'), ('VALIDATION ORDONNATEUR', 'VALIDATION_ORDONNATEUR'), ('REJET ORDONNATEUR', 'REJET_ORDONNATEUR'), ('VALIDATION DECAISSEMENT', 'VALIDATION_DECAISSEMENT'), ('REJET', 'REJET'), ('ARCHIVE', 'ARCHIVE')], default='VALIDATION CAISSE', max_length=255)),
                ('employer_conformite', models.CharField(max_length=255)),
                ('employer_budgetaire', models.CharField(max_length=255)),
                ('employer_ordonnateur', models.CharField(max_length=255)),
                ('employer_caissier', models.CharField(blank=True, max_length=255, null=True)),
                ('montant', models.FloatField()),
                ('observation_conformite', models.TextField(blank=True, null=True)),
                ('observation_budgetaire', models.TextField(blank=True, null=True)),
                ('observation_ordonnateur', models.TextField(blank=True, null=True)),
                ('date_init', models.DateTimeField(blank=True, editable=False)),
                ('date_valid_conformite', models.DateTimeField(blank=True, null=True)),
                ('date_valid_budgetaire', models.DateTimeField(blank=True, null=True)),
                ('date_valid_ordonnateur', models.DateTimeField(blank=True, null=True)),
                ('date_valid_decaissement', models.DateTimeField(blank=True, null=True)),
                ('site', models.CharField(max_length=255)),
                ('entite', models.CharField(max_length=255)),
                ('code_validation', models.CharField(blank=True, max_length=255, null=True)),
                ('expiration_time', models.DateTimeField(blank=True, null=True)),
                ('time_created', models.DateTimeField(blank=True, editable=False)),
                ('time_updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('expense_sheet_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='depenses.expensesheet')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical return to cashier',
                'verbose_name_plural': 'historical return to cashiers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ReturnToCashier',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('employer_initiateur', models.CharField(max_length=255)),
                ('remaining_amount', models.FloatField()),
                ('description', models.TextField()),
                ('num_ref', models.CharField(max_length=255, unique=True)),
                ('num_dossier', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(choices=[('VALIDATION CONFORMITE', 'VALIDATION_CONFORMITE'), ('REJET CONFORMITE', 'REJET_CONFORMITE'), ('VALIDATION BUDGETAIRE', 'VALIDATION_BUDGETAIRE'), ('REJET BUDGETAIRE', 'REJET_BUDGETAIRE'), ('VALIDATION ORDONNATEUR', 'VALIDATION_ORDONNATEUR'), ('REJET ORDONNATEUR', 'REJET_ORDONNATEUR'), ('VALIDATION DECAISSEMENT', 'VALIDATION_DECAISSEMENT'), ('REJET', 'REJET'), ('ARCHIVE', 'ARCHIVE')], default='VALIDATION CAISSE', max_length=255)),
                ('employer_conformite', models.CharField(max_length=255)),
                ('employer_budgetaire', models.CharField(max_length=255)),
                ('employer_ordonnateur', models.CharField(max_length=255)),
                ('employer_caissier', models.CharField(blank=True, max_length=255, null=True)),
                ('montant', models.FloatField()),
                ('observation_conformite', models.TextField(blank=True, null=True)),
                ('observation_budgetaire', models.TextField(blank=True, null=True)),
                ('observation_ordonnateur', models.TextField(blank=True, null=True)),
                ('date_init', models.DateTimeField(auto_now_add=True)),
                ('date_valid_conformite', models.DateTimeField(blank=True, null=True)),
                ('date_valid_budgetaire', models.DateTimeField(blank=True, null=True)),
                ('date_valid_ordonnateur', models.DateTimeField(blank=True, null=True)),
                ('date_valid_decaissement', models.DateTimeField(blank=True, null=True)),
                ('site', models.CharField(max_length=255)),
                ('entite', models.CharField(max_length=255)),
                ('code_validation', models.CharField(blank=True, max_length=255, null=True)),
                ('expiration_time', models.DateTimeField(blank=True, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('expense_sheet_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='depenses.expensesheet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
