# Generated by Django 5.0.1 on 2024-04-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0003_historicalreturntocashier_returntocashier'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesheet',
            name='payment_method',
            field=models.CharField(choices=[('ESPECES', 'ESPECES'), ('CARTE', 'CARTE'), ('VIREMENT', 'VIREMENT'), ('CHEQUE', 'CHEQUE'), ('PAIMENT MOBILE', 'PAIMENT_MOBILE'), ('REJET ORDONNATEUR', 'CRYPTO_MONAIE'), ('PORTE MONAIE ELECTRONIQUE', 'PORTE_MONAIE_ELECTRONIQUE')], default='ESPECES', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalexpensesheet',
            name='payment_method',
            field=models.CharField(choices=[('ESPECES', 'ESPECES'), ('CARTE', 'CARTE'), ('VIREMENT', 'VIREMENT'), ('CHEQUE', 'CHEQUE'), ('PAIMENT MOBILE', 'PAIMENT_MOBILE'), ('REJET ORDONNATEUR', 'CRYPTO_MONAIE'), ('PORTE MONAIE ELECTRONIQUE', 'PORTE_MONAIE_ELECTRONIQUE')], default='ESPECES', max_length=255),
        ),
        migrations.AlterField(
            model_name='expensesheet',
            name='statut',
            field=models.CharField(choices=[('VALIDATION CONFORMITE', 'VALIDATION_CONFORMITE'), ('REJET CONFORMITE', 'REJET_CONFORMITE'), ('VALIDATION BUDGETAIRE', 'VALIDATION_BUDGETAIRE'), ('REJET BUDGETAIRE', 'REJET_BUDGETAIRE'), ('VALIDATION ORDONNATEUR', 'VALIDATION_ORDONNATEUR'), ('REJET ORDONNATEUR', 'REJET_ORDONNATEUR'), ('VALIDATION DECAISSEMENT', 'VALIDATION_DECAISSEMENT'), ('REJET', 'REJET'), ('EN EXECUTION', 'EN_EXECUTION'), ('ARCHIVE', 'ARCHIVE')], default='VALIDATION CONFORMITE', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalexpensesheet',
            name='statut',
            field=models.CharField(choices=[('VALIDATION CONFORMITE', 'VALIDATION_CONFORMITE'), ('REJET CONFORMITE', 'REJET_CONFORMITE'), ('VALIDATION BUDGETAIRE', 'VALIDATION_BUDGETAIRE'), ('REJET BUDGETAIRE', 'REJET_BUDGETAIRE'), ('VALIDATION ORDONNATEUR', 'VALIDATION_ORDONNATEUR'), ('REJET ORDONNATEUR', 'REJET_ORDONNATEUR'), ('VALIDATION DECAISSEMENT', 'VALIDATION_DECAISSEMENT'), ('REJET', 'REJET'), ('EN EXECUTION', 'EN_EXECUTION'), ('ARCHIVE', 'ARCHIVE')], default='VALIDATION CONFORMITE', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalreturntocashier',
            name='statut',
            field=models.CharField(choices=[('VALIDATION CONFORMITE', 'VALIDATION_CONFORMITE'), ('REJET CONFORMITE', 'REJET_CONFORMITE'), ('VALIDATION BUDGETAIRE', 'VALIDATION_BUDGETAIRE'), ('REJET BUDGETAIRE', 'REJET_BUDGETAIRE'), ('VALIDATION ORDONNATEUR', 'VALIDATION_ORDONNATEUR'), ('REJET ORDONNATEUR', 'REJET_ORDONNATEUR'), ('VALIDATION DECAISSEMENT', 'VALIDATION_DECAISSEMENT'), ('REJET', 'REJET'), ('EN EXECUTION', 'EN_EXECUTION'), ('ARCHIVE', 'ARCHIVE')], default='VALIDATION CAISSE', max_length=255),
        ),
        migrations.AlterField(
            model_name='returntocashier',
            name='statut',
            field=models.CharField(choices=[('VALIDATION CONFORMITE', 'VALIDATION_CONFORMITE'), ('REJET CONFORMITE', 'REJET_CONFORMITE'), ('VALIDATION BUDGETAIRE', 'VALIDATION_BUDGETAIRE'), ('REJET BUDGETAIRE', 'REJET_BUDGETAIRE'), ('VALIDATION ORDONNATEUR', 'VALIDATION_ORDONNATEUR'), ('REJET ORDONNATEUR', 'REJET_ORDONNATEUR'), ('VALIDATION DECAISSEMENT', 'VALIDATION_DECAISSEMENT'), ('REJET', 'REJET'), ('EN EXECUTION', 'EN_EXECUTION'), ('ARCHIVE', 'ARCHIVE')], default='VALIDATION CAISSE', max_length=255),
        ),
    ]
