# Generated by Django 5.0.1 on 2024-04-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0005_alter_expensesheet_statut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returntocashier',
            name='expense_sheet_id',
        ),
        migrations.RemoveField(
            model_name='expensesheet',
            name='code_validation',
        ),
        migrations.RemoveField(
            model_name='expensesheet',
            name='date_valid_decaissement',
        ),
        migrations.RemoveField(
            model_name='expensesheet',
            name='employer_caissier',
        ),
        migrations.RemoveField(
            model_name='expensesheet',
            name='expiration_time',
        ),
        migrations.RemoveField(
            model_name='historicalexpensesheet',
            name='code_validation',
        ),
        migrations.RemoveField(
            model_name='historicalexpensesheet',
            name='date_valid_decaissement',
        ),
        migrations.RemoveField(
            model_name='historicalexpensesheet',
            name='employer_caissier',
        ),
        migrations.RemoveField(
            model_name='historicalexpensesheet',
            name='expiration_time',
        ),
        migrations.AlterField(
            model_name='expensesheet',
            name='payment_method',
            field=models.CharField(choices=[('ESPECES', 'ESPECES'), ('CARTE', 'CARTE'), ('VIREMENT', 'VIREMENT'), ('CHEQUE', 'CHEQUE'), ('PAIMENT MOBILE', 'PAIMENT_MOBILE'), ('CRYPTO MONAIE', 'CRYPTO_MONAIE'), ('PORTE MONAIE ELECTRONIQUE', 'PORTE_MONAIE_ELECTRONIQUE')], default='ESPECES', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalexpensesheet',
            name='payment_method',
            field=models.CharField(choices=[('ESPECES', 'ESPECES'), ('CARTE', 'CARTE'), ('VIREMENT', 'VIREMENT'), ('CHEQUE', 'CHEQUE'), ('PAIMENT MOBILE', 'PAIMENT_MOBILE'), ('CRYPTO MONAIE', 'CRYPTO_MONAIE'), ('PORTE MONAIE ELECTRONIQUE', 'PORTE_MONAIE_ELECTRONIQUE')], default='ESPECES', max_length=255),
        ),
        migrations.DeleteModel(
            name='HistoricalReturnToCashier',
        ),
        migrations.DeleteModel(
            name='ReturnToCashier',
        ),
    ]
