# Generated by Django 5.0.1 on 2024-03-27 05:43

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyArticle',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('num_ref', models.CharField(max_length=255, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('sigle', models.CharField(max_length=255)),
                ('type_module', models.CharField(choices=[('DMD', 'DMD'), ('RECETTE', 'RECETTE')], default='DMD', max_length=255)),
                ('site', models.CharField(max_length=255)),
                ('entite', models.CharField(max_length=255)),
                ('create_by', models.CharField(max_length=255)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('num_ref', models.CharField(max_length=255, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('sigle', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('create_by', models.CharField(max_length=255)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('family_article_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articlemanagement.familyarticle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalArticle',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('num_ref', models.CharField(db_index=True, max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('sigle', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('create_by', models.CharField(max_length=255)),
                ('time_created', models.DateTimeField(blank=True, editable=False)),
                ('time_updated', models.DateTimeField(blank=True, editable=False)),
                ('active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('family_article_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='articlemanagement.familyarticle')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical article',
                'verbose_name_plural': 'historical articles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFamilyArticle',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('num_ref', models.CharField(db_index=True, max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('sigle', models.CharField(max_length=255)),
                ('type_module', models.CharField(choices=[('DMD', 'DMD'), ('RECETTE', 'RECETTE')], default='DMD', max_length=255)),
                ('site', models.CharField(max_length=255)),
                ('entite', models.CharField(max_length=255)),
                ('create_by', models.CharField(max_length=255)),
                ('time_created', models.DateTimeField(blank=True, editable=False)),
                ('time_updated', models.DateTimeField(blank=True, editable=False)),
                ('active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical family article',
                'verbose_name_plural': 'historical family articles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
