# Generated by Django 5.0.1 on 2024-04-03 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articlemanagement', '0002_remove_familyarticle_type_module_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familyarticle',
            old_name='type_Module',
            new_name='type_module',
        ),
        migrations.RenameField(
            model_name='historicalfamilyarticle',
            old_name='type_Module',
            new_name='type_module',
        ),
        migrations.RemoveField(
            model_name='familyarticle',
            name='active',
        ),
        migrations.RemoveField(
            model_name='historicalfamilyarticle',
            name='active',
        ),
    ]
