# Generated by Django 5.0.1 on 2024-04-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlemanagement', '0003_rename_type_module_familyarticle_type_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyarticle',
            name='type_module',
            field=models.CharField(choices=[('DMD', 'DMD'), ('BON SORTIE MATERIEL', 'BON SORTIE MATERIEL'), ('DEPENSE', 'DEPENSE'), ('RECETTE', 'RECETTE'), ('RETOUR CAISSE', 'RETOUR CAISSE'), ('APPROVISIONNEMENT CAISSE', 'APPROVISIONNEMENT CAISSE')], default='DMD', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalfamilyarticle',
            name='type_module',
            field=models.CharField(choices=[('DMD', 'DMD'), ('BON SORTIE MATERIEL', 'BON SORTIE MATERIEL'), ('DEPENSE', 'DEPENSE'), ('RECETTE', 'RECETTE'), ('RETOUR CAISSE', 'RETOUR CAISSE'), ('APPROVISIONNEMENT CAISSE', 'APPROVISIONNEMENT CAISSE')], default='DMD', max_length=255),
        ),
    ]
