# from django.utils.translation import ugettext_lazy as _
from django.utils.translation import gettext_lazy as _
from enum import Enum

class StatutExpenseSheet(Enum):
    VALIDATION_CONFORMITE = 'VALIDATION CONFORMITE'
    REJET_CONFORMITE = 'REJET CONFORMITE'
    VALIDATION_BUDGETAIRE = 'VALIDATION BUDGETAIRE'
    REJET_BUDGETAIRE = 'REJET BUDGETAIRE'
    VALIDATION_ORDONNATEUR = 'VALIDATION ORDONNATEUR'
    REJET_ORDONNATEUR = 'REJET ORDONNATEUR'
    VALIDATION_DECAISSEMENT = 'VALIDATION DECAISSEMENT'
    REJET = 'REJET'
    ARCHIVE ='ARCHIVE'
    

BUSINESS_TYPE = [
    ("PRIVATE", _("PRIVATE")),
    ("CORPORATE", _("CORPORATE"))
]

ACCEPT_IMAGE = ["jpg", "jpeg", "png", "JPG", "JPEG", "PNG"]

MAX_IMAGE_SIZE = 1000000

