# Generated by Django 5.0.1 on 2024-04-12 16:33

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('employer_initiateur', models.CharField(max_length=255)),
                ('cashier_id', models.CharField(max_length=255)),
                ('num_ref', models.CharField(max_length=255, unique=True)),
                ('montant', models.FloatField()),
                ('transaction_type', models.CharField(choices=[('CHECKIN', 'CHECKIN'), ('CHECKOUT', 'CHECKOUT')], max_length=255)),
                ('module', models.CharField(choices=[('DMD', 'DMD'), ('BON SORTIE MATERIEL', 'BON_SORTIE_MATERIEL'), ('DEPENSE', 'DEPENSE'), ('RECETTE', 'RECETTE'), ('RETOUR CAISSE', 'RETOUR_CAISSE'), ('APPROVISIONNEMENT CAISSE', 'APPROVISIONNEMENT_CAISSE')], max_length=255)),
                ('status', models.CharField(choices=[('NOT EXECUTED', 'NOT_EXECUTED'), ('EXECUTED', 'EXECUTED')], default='NOT EXECUTED', max_length=255)),
                ('item_id', models.CharField(max_length=255)),
                ('num_dossier', models.CharField(blank=True, max_length=255, null=True)),
                ('employer_beneficiaire', models.CharField(max_length=255, null=True)),
                ('date_valid_beneficiaire', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('code_validation', models.IntegerField(blank=True, null=True)),
                ('expiration_time', models.DateTimeField(blank=True, null=True)),
                ('site', models.CharField(max_length=255)),
                ('entite', models.CharField(max_length=255)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalCashTransaction',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('employer_initiateur', models.CharField(max_length=255)),
                ('cashier_id', models.CharField(max_length=255)),
                ('num_ref', models.CharField(db_index=True, max_length=255)),
                ('montant', models.FloatField()),
                ('transaction_type', models.CharField(choices=[('CHECKIN', 'CHECKIN'), ('CHECKOUT', 'CHECKOUT')], max_length=255)),
                ('module', models.CharField(choices=[('DMD', 'DMD'), ('BON SORTIE MATERIEL', 'BON_SORTIE_MATERIEL'), ('DEPENSE', 'DEPENSE'), ('RECETTE', 'RECETTE'), ('RETOUR CAISSE', 'RETOUR_CAISSE'), ('APPROVISIONNEMENT CAISSE', 'APPROVISIONNEMENT_CAISSE')], max_length=255)),
                ('status', models.CharField(choices=[('NOT EXECUTED', 'NOT_EXECUTED'), ('EXECUTED', 'EXECUTED')], default='NOT EXECUTED', max_length=255)),
                ('item_id', models.CharField(max_length=255)),
                ('num_dossier', models.CharField(blank=True, max_length=255, null=True)),
                ('employer_beneficiaire', models.CharField(max_length=255, null=True)),
                ('date_valid_beneficiaire', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('code_validation', models.IntegerField(blank=True, null=True)),
                ('expiration_time', models.DateTimeField(blank=True, null=True)),
                ('site', models.CharField(max_length=255)),
                ('entite', models.CharField(max_length=255)),
                ('time_created', models.DateTimeField(blank=True, editable=False)),
                ('time_updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical cash transaction',
                'verbose_name_plural': 'historical cash transactions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
