# Generated by Django 5.0.1 on 2024-04-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransaction',
            name='code_validation',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcashtransaction',
            name='code_validation',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
