# Generated by Django 5.0.1 on 2024-04-18 18:00

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('depenses', '0006_remove_returntocashier_expense_sheet_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalReturnToCashier',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('employer_initiateur', models.CharField(max_length=255)),
                ('remaining_balance', models.FloatField()),
                ('description', models.TextField()),
                ('num_dossier', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(choices=[('INITIE', 'INITIE'), ('EN EXECUTION', 'EN_EXECUTION'), ('EXECUTE', 'ARCHIVE')], default='INITIE', max_length=255)),
                ('payment_method', models.CharField(choices=[('ESPECES', 'ESPECES'), ('CARTE', 'CARTE'), ('VIREMENT', 'VIREMENT'), ('CHEQUE', 'CHEQUE'), ('PAIMENT MOBILE', 'PAIMENT_MOBILE'), ('CRYPTO MONAIE', 'CRYPTO_MONAIE'), ('PORTE MONAIE ELECTRONIQUE', 'PORTE_MONAIE_ELECTRONIQUE')], default='ESPECES', max_length=255)),
                ('num_ref', models.CharField(db_index=True, max_length=255)),
                ('site', models.CharField(max_length=255)),
                ('entite', models.CharField(max_length=255)),
                ('time_created', models.DateTimeField(blank=True, editable=False)),
                ('time_updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('expense_sheet_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='depenses.expensesheet')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical return to cashier',
                'verbose_name_plural': 'historical return to cashiers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ReturnToCashier',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('employer_initiateur', models.CharField(max_length=255)),
                ('remaining_balance', models.FloatField()),
                ('description', models.TextField()),
                ('num_dossier', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(choices=[('INITIE', 'INITIE'), ('EN EXECUTION', 'EN_EXECUTION'), ('EXECUTE', 'ARCHIVE')], default='INITIE', max_length=255)),
                ('payment_method', models.CharField(choices=[('ESPECES', 'ESPECES'), ('CARTE', 'CARTE'), ('VIREMENT', 'VIREMENT'), ('CHEQUE', 'CHEQUE'), ('PAIMENT MOBILE', 'PAIMENT_MOBILE'), ('CRYPTO MONAIE', 'CRYPTO_MONAIE'), ('PORTE MONAIE ELECTRONIQUE', 'PORTE_MONAIE_ELECTRONIQUE')], default='ESPECES', max_length=255)),
                ('num_ref', models.CharField(max_length=255, unique=True)),
                ('site', models.CharField(max_length=255)),
                ('entite', models.CharField(max_length=255)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('expense_sheet_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='depenses.expensesheet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
