# Generated by Django 5.0.1 on 2024-04-01 16:43

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityRequest',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('num_ref', models.CharField(max_length=255, unique=True)),
                ('employer_initiateur', models.CharField(max_length=255)),
                ('employer_controleur', models.CharField(max_length=255)),
                ('employer_ordonnateur', models.CharField(max_length=255)),
                ('employer_compta_mat', models.CharField(blank=True, max_length=255, null=True)),
                ('requesting_service', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('VALIDATION CONTROLEUR', 'VALIDATION_CONTROLEUR'), ('REJET CONTROLEUR', 'REJET_CONTROLEUR'), ('VALIDATION ORDONNATEUR', 'VALIDATION_ORDONNATEUR'), ('REJET ORDONNATEUR', 'REJET_ORDONNATEUR'), ('VALIDATION COMPTABLE MATIERE', 'VALIDATION_COMPTABLE_MATIERE'), ('RECU', 'RECU')], default='VALIDATION CONTROLEUR', max_length=255)),
                ('type_produit', models.CharField(choices=[('VALIDATION CONTROLEUR', 'VALIDATION_CONTROLEUR'), ('REJET CONTROLEUR', 'REJET_CONTROLEUR'), ('VALIDATION ORDONNATEUR', 'VALIDATION_ORDONNATEUR'), ('REJET ORDONNATEUR', 'REJET_ORDONNATEUR'), ('VALIDATION COMPTABLE MATIERE', 'VALIDATION_COMPTABLE_MATIERE'), ('RECU', 'RECU')], default='BIEN', max_length=255)),
                ('num_dossier', models.CharField(blank=True, max_length=255, null=True)),
                ('observation_controleur', models.TextField(blank=True, null=True)),
                ('observation_ordonnateur', models.TextField(blank=True, null=True)),
                ('date_valid_controleur', models.DateTimeField(blank=True, null=True)),
                ('date_valid_ordonnateur', models.DateTimeField(blank=True, null=True)),
                ('date_valid_compta_mat', models.DateTimeField(blank=True, null=True)),
                ('site', models.CharField(max_length=255)),
                ('entite', models.CharField(max_length=255)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttachementAvailabilityRequest',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('num_ref', models.CharField(max_length=255, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('availability_requestst_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='availabilityrequest.availabilityrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalAttachementAvailabilityRequest',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('num_ref', models.CharField(db_index=True, max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('availability_requestst_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='availabilityrequest.availabilityrequest')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical attachement availability request',
                'verbose_name_plural': 'historical attachement availability requests',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAvailabilityRequest',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('num_ref', models.CharField(db_index=True, max_length=255)),
                ('employer_initiateur', models.CharField(max_length=255)),
                ('employer_controleur', models.CharField(max_length=255)),
                ('employer_ordonnateur', models.CharField(max_length=255)),
                ('employer_compta_mat', models.CharField(blank=True, max_length=255, null=True)),
                ('requesting_service', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('VALIDATION CONTROLEUR', 'VALIDATION_CONTROLEUR'), ('REJET CONTROLEUR', 'REJET_CONTROLEUR'), ('VALIDATION ORDONNATEUR', 'VALIDATION_ORDONNATEUR'), ('REJET ORDONNATEUR', 'REJET_ORDONNATEUR'), ('VALIDATION COMPTABLE MATIERE', 'VALIDATION_COMPTABLE_MATIERE'), ('RECU', 'RECU')], default='VALIDATION CONTROLEUR', max_length=255)),
                ('type_produit', models.CharField(choices=[('VALIDATION CONTROLEUR', 'VALIDATION_CONTROLEUR'), ('REJET CONTROLEUR', 'REJET_CONTROLEUR'), ('VALIDATION ORDONNATEUR', 'VALIDATION_ORDONNATEUR'), ('REJET ORDONNATEUR', 'REJET_ORDONNATEUR'), ('VALIDATION COMPTABLE MATIERE', 'VALIDATION_COMPTABLE_MATIERE'), ('RECU', 'RECU')], default='BIEN', max_length=255)),
                ('num_dossier', models.CharField(blank=True, max_length=255, null=True)),
                ('observation_controleur', models.TextField(blank=True, null=True)),
                ('observation_ordonnateur', models.TextField(blank=True, null=True)),
                ('date_valid_controleur', models.DateTimeField(blank=True, null=True)),
                ('date_valid_ordonnateur', models.DateTimeField(blank=True, null=True)),
                ('date_valid_compta_mat', models.DateTimeField(blank=True, null=True)),
                ('site', models.CharField(max_length=255)),
                ('entite', models.CharField(max_length=255)),
                ('time_created', models.DateTimeField(blank=True, editable=False)),
                ('time_updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical availability request',
                'verbose_name_plural': 'historical availability requests',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalWordingAvailabilityRequest',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('num_ref', models.CharField(db_index=True, max_length=255)),
                ('beneficiary_id', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('qantity', models.IntegerField()),
                ('motif', models.CharField(max_length=255)),
                ('date_use_start', models.DateTimeField()),
                ('quantity_rewind', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('availability_requestst_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='availabilityrequest.availabilityrequest')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical wording availability request',
                'verbose_name_plural': 'historical wording availability requests',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WordingAvailabilityRequest',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('num_ref', models.CharField(max_length=255, unique=True)),
                ('beneficiary_id', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('qantity', models.IntegerField()),
                ('motif', models.CharField(max_length=255)),
                ('date_use_start', models.DateTimeField()),
                ('quantity_rewind', models.DateTimeField(blank=True, null=True)),
                ('availability_requestst_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='availabilityrequest.availabilityrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
