# Generated by Django 5.0.1 on 2024-04-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availabilityrequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityrequest',
            name='Priority',
            field=models.IntegerField(blank=True, choices=[(1, 'WEAK'), (2, 'MEDIUM'), (3, 'HIGH')], null=True),
        ),
        migrations.AddField(
            model_name='historicalavailabilityrequest',
            name='Priority',
            field=models.IntegerField(blank=True, choices=[(1, 'WEAK'), (2, 'MEDIUM'), (3, 'HIGH')], null=True),
        ),
        migrations.AlterField(
            model_name='availabilityrequest',
            name='type_produit',
            field=models.CharField(choices=[('BIEN', 'BIEN'), ('SERVICE', 'SERVICE')], default='BIEN', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalavailabilityrequest',
            name='type_produit',
            field=models.CharField(choices=[('BIEN', 'BIEN'), ('SERVICE', 'SERVICE')], default='BIEN', max_length=255),
        ),
    ]
