# Generated by Django 5.0.1 on 2024-04-09 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availabilityrequest', '0002_availabilityrequest_priority_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availabilityrequest',
            old_name='Priority',
            new_name='priority',
        ),
        migrations.RenameField(
            model_name='historicalavailabilityrequest',
            old_name='Priority',
            new_name='priority',
        ),
    ]
